### ISSUE TITLE
I never know GitHub Pages with CNAME don't have SSL certificate

### ISSUE THREAD

**Issue by patarapolw** [maestromac/maestromac.github.io#1]
![Screen Shot 2563-06-15 at 07 31 24](https://user-images.githubusercontent.com/21255931/84607993-7c50e000-aeda-11ea-9907-5c00a80f7c91.png)

You might have to somehow contact GitHub Pages Support, or Microsoft.

Not seems to be a problem with Netlify, AFAIK.

**Comment by maestromac** [comment]
Just fixed it. Thanks for this @patarapolw !
